import { mkdir, writeFile, rm } from "fs/promises";
import { join, resolve } from "path";
import { existsSync } from "fs";
import { fileURLToPath } from "url";

const SERVICE_DIR = fileURLToPath(new URL(".", import.meta.url));
const API_ROOT_DIR = resolve(SERVICE_DIR, "../..");
const SERVERS_DIR = resolve(API_ROOT_DIR, process.env.SERVERS_DIR || "./servers");
const HOST_SERVERS_DIR = process.env.HOST_SERVERS_DIR || "";

interface ComposeConfig {
  serverId: string;
  name: string;
  port: number;
  version: string;
  type: string;
  memoryMb: number;
}

function getServerType(type: string): string {
const typeMap: Record<string, string> = {
    vanilla: "VANILLA",
    paper: "PAPER",
    fabric: "FABRIC",
    forge: "FORGE",
    spigot: "SPIGOT",
    bukkit: "BUKKIT",
  };
  return typeMap[type.toLowerCase()] || "VANILLA";
}

function toDockerVolumePath(path: string): string {
  return path.replace(/\\/g, "/");
}

function getHostServerDir(serverId: string): string | null {
  if (!HOST_SERVERS_DIR.trim()) return null;
  return resolve(HOST_SERVERS_DIR, serverId);
}

function generateComposeYml(config: ComposeConfig): string {
  const serverType = getServerType(config.type);
  const hostServerDir = getHostServerDir(config.serverId);
  const volumeSource = hostServerDir ? `${toDockerVolumePath(join(hostServerDir, "data"))}:/data` : "./data:/data";

  return `# Auto-generated by myCubeKub — do not edit manually
services:
  minecraft:
    container_name: mcserver-${config.serverId}
    image: itzg/minecraft-server
    ports:
      - "${config.port}:25565"
    environment:
      EULA: "TRUE"
      TYPE: "${serverType}"
      VERSION: "${config.version}"
      MEMORY: "${config.memoryMb}M"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "mycubekub"
      RCON_PORT: "25575"
    volumes:
      - ${volumeSource}
    restart: unless-stopped
    stdin_open: true
    tty: true
`;
}

/**
 * Get the server directory path
 */
export function getServerDir(serverId: string): string {
  return join(SERVERS_DIR, serverId);
}

/**
 * Create server directory structure and docker-compose.yml
 */
export async function createServerFiles(config: ComposeConfig): Promise<string> {
  const serverDir = getServerDir(config.serverId);
  const dataDir = join(serverDir, "data");

  // Create directories
  await mkdir(dataDir, { recursive: true });

  // Generate and write docker-compose.yml
  const composeContent = generateComposeYml(config);
  await writeFile(join(serverDir, "docker-compose.yml"), composeContent, "utf-8");

  return serverDir;
}

/**
 * Update docker-compose.yml with new config
 */
export async function updateServerFiles(config: ComposeConfig): Promise<void> {
  const serverDir = getServerDir(config.serverId);
  const composeContent = generateComposeYml(config);
  await writeFile(join(serverDir, "docker-compose.yml"), composeContent, "utf-8");
}

/**
 * Delete server directory and all its contents
 */
export async function deleteServerFiles(serverId: string): Promise<void> {
  const serverDir = getServerDir(serverId);
  if (existsSync(serverDir)) {
    await rm(serverDir, { recursive: true, force: true });
  }
}

/**
 * Read server.properties from a server's data directory
 */
export async function readServerProperties(serverId: string): Promise<Record<string, string>> {
  const propsPath = join(getServerDir(serverId), "data", "server.properties");

  try {
    const content = await Bun.file(propsPath).text();
    const props: Record<string, string> = {};

    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.substring(0, eqIdx).trim();
      const value = trimmed.substring(eqIdx + 1).trim();
      props[key] = value;
    }

    return props;
  } catch {
    return {};
  }
}

/**
 * Write server.properties to a server's data directory
 */
export async function writeServerProperties(
  serverId: string,
  properties: Record<string, string>
): Promise<void> {
  const propsPath = join(getServerDir(serverId), "data", "server.properties");

  // Read existing content to preserve comments and ordering
  let existingLines: string[] = [];
  try {
    const content = await Bun.file(propsPath).text();
    existingLines = content.split("\n");
  } catch {
    // File doesn't exist yet, start fresh
  }

  const updatedKeys = new Set<string>();
  const outputLines: string[] = [];

  // Update existing lines
  for (const line of existingLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      outputLines.push(line);
      continue;
    }
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) {
      outputLines.push(line);
      continue;
    }
    const key = trimmed.substring(0, eqIdx).trim();
    if (key in properties) {
      outputLines.push(`${key}=${properties[key]}`);
      updatedKeys.add(key);
    } else {
      outputLines.push(line);
    }
  }

  for (const [key, value] of Object.entries(properties)) {
    if (!updatedKeys.has(key)) {
      outputLines.push(`${key}=${value}`);
    }
  }

  await writeFile(propsPath, outputLines.join("\n"), "utf-8");
}

export { SERVERS_DIR };
