import { mkdir, writeFile, rm } from "fs/promises";
import { randomBytes } from "crypto";
import { dirname, join, resolve } from "path";
import { existsSync } from "fs";
import { fileURLToPath } from "url";

const SERVICE_DIR = fileURLToPath(new URL(".", import.meta.url));
const API_ROOT_DIR = resolve(SERVICE_DIR, "../..");
const SERVERS_DIR = resolve(API_ROOT_DIR, process.env.SERVERS_DIR || "./servers");
const HOST_SERVERS_DIR = process.env.HOST_SERVERS_DIR || "";

interface ComposeConfig {
  serverId: string;
  name: string;
  port: number;
  version: string;
  type: string;
  memoryMb: number;
}

function getServerType(type: string): string {
const typeMap: Record<string, string> = {
    vanilla: "VANILLA",
    paper: "PAPER",
    fabric: "FABRIC",
    forge: "FORGE",
    spigot: "SPIGOT",
    bukkit: "BUKKIT",
  };
  return typeMap[type.toLowerCase()] || "VANILLA";
}

function toDockerVolumePath(path: string): string {
  return path.replace(/\\/g, "/");
}

function getHostServerDir(serverId: string): string | null {
  if (!HOST_SERVERS_DIR.trim()) return null;
  return resolve(HOST_SERVERS_DIR, serverId);
}

function generateComposeYml(config: ComposeConfig): string {
  const serverType = getServerType(config.type);
  const hostServerDir = getHostServerDir(config.serverId);
  const volumeSource = hostServerDir ? `${toDockerVolumePath(join(hostServerDir, "data"))}:/data` : "./data:/data";

  return `# Auto-generated by myCubeKub — do not edit manually
services:
  minecraft:
    container_name: mcserver-${config.serverId}
    image: itzg/minecraft-server
    ports:
      - "${config.port}:25565"
    environment:
      EULA: "TRUE"
      TYPE: "${serverType}"
      VERSION: "${config.version}"
      MEMORY: "${config.memoryMb}M"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "mycubekub"
      RCON_PORT: "25575"
    volumes:
      - ${volumeSource}
    restart: unless-stopped
    stdin_open: true
    tty: true
`;
}

/**
 * Get the server directory path
 */
export function getServerDir(serverId: string): string {
  return join(SERVERS_DIR, serverId);
}

/**
 * Create server directory structure and docker-compose.yml
 */
export async function createServerFiles(config: ComposeConfig): Promise<string> {
  const serverDir = getServerDir(config.serverId);
  const dataDir = join(serverDir, "data");

  // Create directories
  await mkdir(dataDir, { recursive: true });

  // Generate and write docker-compose.yml
  const composeContent = generateComposeYml(config);
  await writeFile(join(serverDir, "docker-compose.yml"), composeContent, "utf-8");

  return serverDir;
}

/**
 * Update docker-compose.yml with new config
 */
export async function updateServerFiles(config: ComposeConfig): Promise<void> {
  const serverDir = getServerDir(config.serverId);
  const composeContent = generateComposeYml(config);
  await writeFile(join(serverDir, "docker-compose.yml"), composeContent, "utf-8");
}

/**
 * Delete server directory and all its contents
 */
export async function deleteServerFiles(serverId: string): Promise<void> {
  const serverDir = getServerDir(serverId);
  if (existsSync(serverDir)) {
    await rm(serverDir, { recursive: true, force: true });
  }
}

/**
 * Read server.properties from a server's data directory
 */
export async function readServerProperties(serverId: string): Promise<{ properties: Record<string, string>; exists: boolean }> {
  const propsPath = join(getServerDir(serverId), "data", "server.properties");
  const exists = existsSync(propsPath);

  try {
    const content = await Bun.file(propsPath).text();
    const props: Record<string, string> = {};

    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.substring(0, eqIdx).trim();
      const value = trimmed.substring(eqIdx + 1).trim();
      props[key] = value;
    }

    return {
      properties: props,
      exists,
    };
  } catch {
    return {
      properties: {},
      exists,
    };
  }
}

/**
 * Write server.properties to a server's data directory
 */
export async function writeServerProperties(
  serverId: string,
  properties: Record<string, string>
): Promise<void> {
  const propsPath = join(getServerDir(serverId), "data", "server.properties");
  await mkdir(dirname(propsPath), { recursive: true });

  // Read existing content to preserve comments and ordering
  let existingLines: string[] = [];
  try {
    const content = await Bun.file(propsPath).text();
    existingLines = content.split("\n");
  } catch {
    // File doesn't exist yet, start fresh
  }

  const updatedKeys = new Set<string>();
  const outputLines: string[] = [];

  // Update existing lines
  for (const line of existingLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      outputLines.push(line);
      continue;
    }
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) {
      outputLines.push(line);
      continue;
    }
    const key = trimmed.substring(0, eqIdx).trim();
    if (key in properties) {
      outputLines.push(`${key}=${properties[key]}`);
      updatedKeys.add(key);
    } else {
      outputLines.push(line);
    }
  }

  for (const [key, value] of Object.entries(properties)) {
    if (!updatedKeys.has(key)) {
      outputLines.push(`${key}=${value}`);
    }
  }

  await writeFile(propsPath, outputLines.join("\n"), "utf-8");
}

function formatPropertiesTimestamp(date = new Date()) {
  const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const day = weekdays[date.getUTCDay()];
  const month = months[date.getUTCMonth()];
  const dayOfMonth = String(date.getUTCDate()).padStart(2, "0");
  const hours = String(date.getUTCHours()).padStart(2, "0");
  const minutes = String(date.getUTCMinutes()).padStart(2, "0");
  const seconds = String(date.getUTCSeconds()).padStart(2, "0");
  const year = date.getUTCFullYear();

  return `${day} ${month} ${dayOfMonth} ${hours}:${minutes}:${seconds} UTC ${year}`;
}

function buildDefaultServerPropertiesContent(port: number) {
  const managementServerSecret = randomBytes(24).toString("base64url");
  const lines = [
    "#Minecraft server properties",
    `#${formatPropertiesTimestamp()}`,
    "accepts-transfers=false",
    "allow-flight=false",
    "broadcast-console-to-ops=true",
    "broadcast-rcon-to-ops=true",
    "bug-report-link=",
    "difficulty=easy",
    "enable-code-of-conduct=false",
    "enable-jmx-monitoring=false",
    "enable-query=false",
    "enable-rcon=true",
    "enable-status=true",
    "enforce-secure-profile=true",
    "enforce-whitelist=false",
    "entity-broadcast-range-percentage=100",
    "force-gamemode=false",
    "function-permission-level=2",
    "gamemode=survival",
    "generate-structures=true",
    "generator-settings={}",
    "hardcore=false",
    "hide-online-players=false",
    "initial-disabled-packs=",
    "initial-enabled-packs=vanilla",
    "level-name=world",
    "level-seed=",
    "level-type=minecraft\\:normal",
    "log-ips=true",
    "management-server-allowed-origins=",
    "management-server-enabled=false",
    "management-server-host=localhost",
    "management-server-port=0",
    `management-server-secret=${managementServerSecret}`,
    "management-server-tls-enabled=true",
    "management-server-tls-keystore=",
    "management-server-tls-keystore-password=",
    "max-chained-neighbor-updates=1000000",
    "max-players=20",
    "max-tick-time=60000",
    "max-world-size=29999984",
    "motd=A Minecraft Server",
    "network-compression-threshold=256",
    "online-mode=true",
    "op-permission-level=4",
    "pause-when-empty-seconds=60",
    "player-idle-timeout=0",
    "prevent-proxy-connections=false",
    `query.port=${port}`,
    "rate-limit=0",
    "rcon.password=mycubekub",
    "rcon.port=25575",
    "region-file-compression=deflate",
    "require-resource-pack=false",
    "resource-pack=",
    "resource-pack-id=",
    "resource-pack-prompt=",
    "resource-pack-sha1=",
    "server-ip=",
    `server-port=${port}`,
    "simulation-distance=10",
    "spawn-protection=16",
    "status-heartbeat-interval=0",
    "sync-chunk-writes=true",
    "text-filtering-config=",
    "text-filtering-version=0",
    "use-native-transport=true",
    "view-distance=10",
    "white-list=false",
  ];

  return `${lines.join("\n")}\n`;
}

export async function createDefaultServerProperties(serverId: string, port: number) {
  const propsPath = join(getServerDir(serverId), "data", "server.properties");
  await mkdir(dirname(propsPath), { recursive: true });
  await writeFile(propsPath, buildDefaultServerPropertiesContent(port), "utf-8");
  return readServerProperties(serverId);
}

export { SERVERS_DIR };
